package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize atlas configuration",
	Long:  `Initialize atlas configuration with server URLs and credentials`,
	RunE: func(cmd *cobra.Command, args []string) error {
		configDir := os.Getenv("XDG_CONFIG_HOME")
		if configDir == "" {
			home, err := os.UserHomeDir()
			if err != nil {
				return err
			}
			configDir = filepath.Join(home, ".config")
		}

		atlasConfigDir := filepath.Join(configDir, "atlas")
		if err := os.MkdirAll(atlasConfigDir, 0755); err != nil {
			return fmt.Errorf("creating config directory: %w", err)
		}

		configFile := filepath.Join(atlasConfigDir, "config.yaml")

		// Check if config already exists
		if _, err := os.Stat(configFile); err == nil {
			fmt.Printf("Config file already exists at: %s\n", configFile)
			fmt.Println("Edit it manually or delete it to reinitialize.")
			return nil
		}

		// Create default config
		defaultConfig := `# Atlas CLI Configuration
# Generated by 'atlas init'

# Global username (can be overridden per service)
username: %s

# Bitbucket configuration
bitbucket:
  server: %s
  token: %s

# JIRA configuration  
jira:
  server: %s
  token: %s
  default_project: %s

# Confluence configuration (future)
confluence:
  server: https://confluence.yourdomain.com
  token: your-confluence-token
`

		username := viper.GetString("username")
		if username == "" {
			username = "your.username"
		}

		bitbucketServer := viper.GetString("bitbucket.server")
		if bitbucketServer == "" {
			bitbucketServer = "https://git.yourdomain.com"
		}

		bitbucketToken := viper.GetString("bitbucket.token")
		if bitbucketToken == "" {
			bitbucketToken = "your-bitbucket-token"
		}

		jiraServer := viper.GetString("jira.server")
		if jiraServer == "" {
			jiraServer = "https://jira.yourdomain.com"
		}

		jiraToken := viper.GetString("jira.token")
		if jiraToken == "" {
			jiraToken = "your-jira-token"
		}

		defaultProject := viper.GetString("jira.default_project")
		if defaultProject == "" {
			defaultProject = "PROJ"
		}

		content := fmt.Sprintf(defaultConfig, username, bitbucketServer, bitbucketToken,
			jiraServer, jiraToken, defaultProject)

		if err := os.WriteFile(configFile, []byte(content), 0600); err != nil {
			return fmt.Errorf("writing config file: %w", err)
		}

		fmt.Printf("Configuration initialized at: %s\n", configFile)
		fmt.Println("\nNext steps:")
		fmt.Println("1. Edit the config file with your actual credentials")
		fmt.Println("2. For JIRA, use Bearer tokens (Personal Access Tokens)")
		fmt.Println("3. For Bitbucket, use API tokens")
		fmt.Println("\nExample commands:")
		fmt.Println("  atlas pr list PROJECT/REPO")
		fmt.Println("  atlas issue list --project PROJ")

		return nil
	},
}

func init() {
	rootCmd.AddCommand(initCmd)
}
